#!/bin/bash

#  updated on 17.05.2015 16:11:02

#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  

#################################################################
# Design based on IceFox script                                 #
# Modified, adapted and improved by pekman and excalibur1234    #
# translation by spylinux					#
# Pmenu and Downgrade support added by Chrysostomus		#
# Contact and suggestions: pekman@openmailbox.org               #
# Freenode: #manjaropek #manjaro-geek #manjaro			#
# Topic discussion 						#
#			http://polr.me/pacli1			#
#			http://polr.me/pacli2			#
#################################################################

function help_text() {
	cat 	<<-EOF
::The helptext comes here
	EOF
}

# set colors
RED='\e[41m'
BLUE='\e[44m'
ORANGE='\e[46m'
NC='\e[0m'
    while true; do
    clear
    echo ""
    echo -e "                             $NC ::Pacli - Package manager:: $NC "
    echo ""
    echo -e ""
    echo -e " ┌────────────────────────────────────────────────────────────────────────────┐"
    echo -e " │  $NC  1 $NC  Update System                       $NC  2 $NC  Optimize Mirrors          │"
    echo -e " │  $NC  3 $NC  Optimize Database                   $NC  4 $NC  Clean Package Cache       │"
    echo -e " │  $NC  5 $NC  Search Package                      $NC  6 $NC  Package Information       │"
    echo -e " │  $NC  7 $NC  Install Package                     $NC  8 $NC  Detail Installed Packages │"
    echo -e " │  $NC  9 $NC  Remove Package                      $NC 10 $NC  Remove Package + Deps     │"
    echo -e " │  $NC 11 $NC  List Orphaned Packages              $NC 12 $NC  Remove Orphaned Packages  │"
    echo -e " │  $NC 13 $NC  Local List                          $NC 14 $NC  Dependencies Tree         │"
    echo -e " │  $NC 15 $NC  Installed Packages                  $NC 16 $NC  Fix Errors                │"
    echo -e " │  $NC 17 $NC  Downgrade Packages                  $NC 18 $NC  Help                      │"
    echo " └────────────────────────────────────────────────────────────────────────────┘"
    echo ""
    echo " ┌────────────────────────────────────────────────────────────────────────────┐"
    echo -e " │  $NC 19 $NC  Update AUR                          $NC 20 $NC  Search + Install from AUR │"
    echo -e " │  $NC 21 $NC  Install from AUR                    $NC 22 $NC  List Installed from AUR   │"
    echo " └────────────────────────────────────────────────────────────────────────────┘"
    echo ""
    echo -e "    $NC Select a number between 1 and 22 and press [Enter]$NC $NC - 0 Exit Pacli$NC"
    echo ""
    read choix
    case $choix in
        1)
            echo
            sudo pacman -Syyuu
            echo ""
            echo -e "$NC Your system is updated. To return to pacli press [Enter] $NC"
            read
            ;;
        2)
            echo
            sudo pacman-mirrors -g && sudo pacman -Syy
            echo ""
            echo -e "$NC Fastest mirror chosen. To return to pacli press [Enter] $NC"
            read
            ;;
        3)
            echo
            sudo pacman-optimize
            echo ""
            echo -e "$NC Pacman Database optimized. To return to pacli press [Enter] $NC"
            read
            ;;
        4)
            echo
            paccache -ruk0
	    paccache -rk2
            echo ""
            echo -e "$NC Unneeded and old package versions removed. To return to pacli press [Enter] $NC"
            read
            ;;
        5)
            echo ""
            echo "Do you want to search a package? Put the name below and press [Enter]"
            echo ""
            pacman -Ss $(pacman -Slq | pmenu -p 'select package to search >')
            echo ""
            echo -e "$NC The search is complete. To return to pacli press [Enter] $NC"
            read
            ;;
        6)
            echo ""
            echo "Do you want to check specific information about a package? Put the name below and press [Enter]"
            echo ""
            pacman -Si $(pacman -Slq | pmenu -p 'select package to search >')
            echo ""
            echo -e "$NC The search for information ended. To return to pacli press [Enter] $NC"
            read 
			;;
        7)
            echo ""
            echo "Do you want to install a package? Put the name below and press [Enter]"
            echo ""
            sudo pacman -S $(pacman -Slq | pmenu -p 'select package to install >')
            echo ""
            echo -e "$NC The package installation is finished. To return to pacli press [Enter] $NC"
            read
            ;;
        8)
            echo ""
            echo "Do you want to check specific information about a package?  Put the name below and press [Enter]"
            echo ""
            pacman -Qi $(pacman -Qq | pmenu -p 'select a package >')
            echo ""
            echo -e "$NC All information displayed. To return to pacli press [Enter] $NC"
            read
            ;;
        9)
            echo ""
            echo "Select package to uninstall. All Dependencies will be kept as orphans."
            echo ""
            sudo pacman -R $(pacman -Qq | pmenu -p 'select package to uninstall >')
            echo ""
            echo -e "$NC Action completed. To return to pacli press [Enter] $NC"
            read
            ;;
        10)
	    echo ""
            echo "Select package to uninstall. All of its dependencies shall be removed."
            echo ""
            sudo pacman -Rsn $(pacman -Qq | pmenu -p 'select package to uninstall >')
            echo ""
            echo -e "$NC Action completed. To return to pacli press [Enter] $NC"
            read
            ;;
        11)
            echo ""
            echo "Display all orphan packages"
            pacman -Qqdt
            echo ""
            echo -e "$NC Checking completed. To return to pacli press [Enter] $NC"
            read        
            ;;
        12)
            echo ""
            echo "Uninstalling orphan packages with their depencies."
            echo ""
            sudo pacman -Rns $(pacman -Qqdt)
            echo ""
            echo -e "$NC Task completed. To return to pacli press [Enter] $NC"
            read
            ;;
        13)
            echo ""
            echo "Select package to list all local files of."
            echo ""
            pacman -Ql $(pacman -Qq | pmenu -p 'select a package >')
            echo ""
            echo -e "$NC Task completed. To return to pacli press [Enter] $NC"
            read 
            ;;
        14)
            echo ""
            echo "Select a package whose dependency tree is to be displayed."
            echo ""
            pactree $(pacman -Qq | pmenu -p 'select a package >')
            echo ""
            echo -e "$NC Task completed. To return to pacli press [Enter] $NC"
            read
            ;;
        15)
            echo ""
            pacman -Qet
            echo ""
            echo -e "$NC Task completed. To return to pacli press [Enter] $NC"
            read     
            ;;
            
        16)
            echo ""
            sudo rm -f /var/lib/pacman/db.lck && sudo pacman-mirrors -g && sudo pacman -Syy
            echo ""
            echo -e "$NC All Pacman errors fixed. Now press [Enter] $NC"
            read     
            ;;
        17)
            echo ""
            echo ""
            downgrade $(pacman -Qq | pmenu -p 'select package to downgrade >')
            echo -e "$NC Task completed. To return to pacli press [Enter] $NC"
            read     
            ;;
        18)
            echo ""
            echo ""
            help_text
            echo ""
            echo -e "$NC To return to pacli press [Enter] $NC"
            read
            ;;
        19)
            echo ""
            echo ""
            yaourt -Syyuua
            echo ""
            echo -e "$NC There is nothing else to do. To return to pacli press [Enter] $NC"
            read     
            ;;
        20)
            echo ""
            echo "Enter name of package to be searched and installed from AUR and press [Enter] to continue"
            echo ""
            read Packcage
            yaourt $Packcage
            echo ""
            echo -e "$NC Task completed. To return to pacli press [Enter] $NC"
            read 
            ;;
        21)
            echo ""
            echo "Enter name of package to be installed from AUR and press [Enter] to continue"
            echo ""
            read Packcage
            yaourt -S $Packcage
            echo ""
            echo -e "$NC Task completed. To return to pacli press [Enter] $NC"
            read 
            ;;
        22)
            echo ""
            pacman -Qem
            echo ""
            echo -e "$NC Task completed. To return to pacli press [Enter] $NC"
            read     
            ;;     
        0)
            clear && exit
            read
            ;;
        *)
            echo -e "$RED Wrong option $NC"
            echo "Wait and try again later..."
            echo ""
            sleep 3
            clear
            ;;
    esac
    done
fi
